version: "3"
services:
  eosio:
    image: eosio/eos:dawn3x
    ports:
      - "8888:8888"
      - "9876:9876"
    command: /opt/eosio/bin/nodeosd.sh --resync-blockchain
    volumes:
      - ./eosio-volume/config:/opt/eosio/bin/data-dir
      - ./eosio-volume/data:/opt/eosio/var
  echo:
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - "5433:5432"